/* TRANSACTION */
-- MYSQL 기본적으로 COMMIT이 자동으로 되므로 수동으로 조절하고 싶다면 AUTO COMMIT 설정을 바꿔 주어야 한다.

-- AUTOCOMMIT 활성화
SET AUTOCOMMIT = 1;
SET AUTOCOMMIT = ON;

-- AUTOCOMMIT 비활성화
SET AUTOCOMMIT = 0;
SET AUTOCOMMIT = OFF;

-- START TRANSACTION 구문을 작성하고 DML 작업 수행 후 COMMIT 또는 ROLLBACK을 하면 된다.
-- COMMIT 이후에도 ROLLBACK을 해도 ROLLBACK이 적용되지 않는다.
START TRANSACTION;

SELECT * FROM TBL_MENU;

INSERT INTO TBL_MENU VALUES(NULL, '바나나해장국', 8500, 4, 'Y');
UPDATE TBL_MENU SET MENU_NAME = '수정된메뉴' WHERE MENU_CODE = 5;
DELETE FROM TBL_MENU WHERE MENU_CODE = 7;

COMMIT;
ROLLBACK;